name: flygincanada
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7136061014607549
title: FLY GIN CANADA
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000001'
    - '#bfbcbd'
    - '#ff0043'
    - '#827f8c'
    - '#ff4659'
  brandStrength: 0.5
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
